version: "3.8"

services:
  web:
    container_name: projeto-pedido
    build:
      context: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASS: projeto-pedido
      MONGO_PORT: 27017
      MONGO_COLLECTION: admin
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: projeto-pedido
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none

volumes:
  mongo-data:
