version: "3.8"

services:
  web:
    container_name: projeto-pedido
    build:
      context: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      MONGO_PASS: projeto-pedido
      MONGO_PORT: 27017
      MONGO_COLLECTION: admin

      CHOKIDAR_USEPOLLING: "true"
      MARIADB_HOST: maria-db
      MARIADB_USER: root
      MARIADB_PASS: 12345678
      MARIADB_DATABASE: projeto-pedidos
      MARIADB_PORT: 3306
      MP_URL: https://api.mercadopago.com/v1/
      MP_CLIENT_ID: TEST-427f8e8c-d6ca-4000-ab9b-95b3a2e554f7
      MP_CLIENT_SECRET: TEST-8926445123950097-011307-ee5dc50bf53c38a033fe5da4c9acc9c1__LD_LB__-209191463
    depends_on:
      # - mongo
      - maria-db

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27020:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: projeto-pedido
  #   volumes:
  #     - mongo-data:/data/db
  #   logging:
  #     driver: none

  maria-db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: projeto-pedidos
      MARIADB_USER: root
      MARIADB_PASSWORD: 12345678
      MARIADB_ROOT_PASSWORD: 12345678
    ports:
      - 3321:3306

volumes:
  # mongo-data:
  mariadb-data:
