version: "3.8"

services:
  web:
    container_name: projeto-pedido
    build:
      context: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASS: projeto-pedido
      MONGO_PORT: 27017
      MONGO_COLLECTION: admin
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
      MARIADB_HOST: maria-db
      MARIADB_USER: root
      MARIADB_PASS: 12345678
      MARIADB_DATABASE: projeto-pedidos
      MARIADB_PORT: 3306
    depends_on:
      - mongo
      - maria-db

  mongo:
    image: mongo
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: projeto-pedido
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none

  maria-db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: projeto-pedidos
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: userMariaDbPass
      MARIADB_ROOT_PASSWORD: 12345678
    ports:
      - 3321:3306

volumes:
  mongo-data:
  mariadb-data:
