openapi: '3.0.2'
info:
  title: Projeto Pedidos
  version: '1.0'
servers:
  - url: http://localhost:3000/api/v1
paths:
  /user/auth:
    post:
      summary: Retorna o token para autenticação.
      description: Infoma o token para autenticação o tempo de expiração e qual o tipo de utilização 
      responses:
        '200':
          description: retorna um token para autenticação
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Auth'
  /customers:
    get:
      summary: Recupera uma lista de usuários.
      description: Recupera uma lista de usuarios no sistema.
      parameters:
        - in: query
          name: email
          schema:
            type: string
          description: recupera os dados de um usuário pelo email especifico ou parcial
        - in: query
          name: cpf_cnpj
          schema:
            type: string
          description: recupera os dados de um usuário pelo documento em especifico ou parcial
      responses:
        '200':
          description: retorna uma lista de itens
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Cria um novo usuário.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                cpf_cnpj:
                  type: string
                  format: number
                  example: "000.000.000-00"
              required:
                - "name"
                - "email"
                - "cpf_cnpj"
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
  /customers/{id}:
    get:
      summary: Recupera um usuário pelo ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID do cliente
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
    put:
      summary: Atualiza os dados de um usuário.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID do cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                cpf_cnpj:
                  type: string
                  format: number
                  example: "000.000.000-00"
              required:
                - "name"
                - "email"
                - "cpf_cnpj"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'         
    delete:
      summary: Deleta um usuário.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID do cliente
      responses:
        '204':
          description: OK
  /customers/{cpfcnpj}/identify:
    get:
      summary: Recupera um usuário pelo número do documento
      parameters:
        - in: path
          name: cpfcnpj
          schema:
            type: integer
          required: true
          description: CPF/CNPJ do cliente
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'

components:
  securitySchemes:
     BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    Auth:
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjYsImV4cCI6MTY5NzkyMjAwNjA1MywibmFtZSI6IkJydW5vIEJsYXV6aXVzIHNjaHVpbmR0IiwiZW1haWwiOiJicnVub2JsYXV6aXVzQGdtYWlsLmNvbSJ9.QVh-6NZB0gKTgiS2xBKNdgau2ZS0dOqyCnxNWFxAGW8
        expires_in:
          type: number
          example: 3600
        scope:
          type: string
          example: customScope
        token_type:
          type: string
          example: Bearer
    Customer:
      properties:
        id:
          type: integer
        name:
          type: string
          example: Admin
        email:
          type: string
          format: email
          example: admin@teste.com
        cpf_cnpj:
          type: string
          format: number
          example: "000.000.000-00"
      required:
        - "name"
        - "email"
        - "cpf_cnpj"

security:
  - BearerAuth: []