apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data-volume
spec:
  capacity:
    storage: 1Gi  # Adjust the size based on your requirements
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/mariadb  # Update this path to your external volume path
  storageClassName: default  # Defina o nome da sua classe de armazenamento
