apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size based on your requirements
  storageClassName: default  # Defina o nome da sua classe de armazenamento
  volumeName: mariadb-data-volume  # Adicionado para referenciar o PersistentVolume correto