apiVersion: v1
kind: Pod
metadata:
  name: db-deployment
  labels:
    app: db-deployment
spec:
  containers:
  - name: db-deployment-container
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value:  "123456"
    - name: MYSQL_DATABASE
      value: projeto-pedidos
    - name: MYSQL_PASSWORD
      value:  "123456"
    ports:
    - containerPort: 3306
